apiVersion: v2
name: update-route53
description: A Helm chart for installing update-route53 in Kubernetes
type: application
version: 0.1.7
appVersion: "1.0.8"
maintainers:
  - name: JP Flouret
    email: jpflouret@gmail.com
